# Generated by Django 3.1.1 on 2020-10-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(verbose_name='Url de la imagen'),
        ),
    ]
