# Generated by Django 3.1.1 on 2020-10-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20201019_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estaEnOferta',
            field=models.BooleanField(default=False, verbose_name='Está en oferta?'),
        ),
    ]
